on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

name: Check pull request

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: pando85/Android-Password-Store/.github/reusable-workflows/setup-gradle@b5a108731ef2c45cee4fe546f07eaf674948f6ce # main
        with:
          java-version: 21

      - name: Check codestyle
        shell: bash
        run: ./gradlew spotlessCheck

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build report (check-codestyle)
          path: build/reports/kotlin-build/

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: pando85/Android-Password-Store/.github/reusable-workflows/setup-gradle@b5a108731ef2c45cee4fe546f07eaf674948f6ce # main
        with:
          java-version: 21

      - name: Run unit tests
        shell: bash
        run: ./gradlew test -PslimTests

      - name: (Fail-only) Upload test report
        if: "${{ failure() }}"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Test report (unit-tests)
          path: |
            app/build/reports
            passkeys/core/build/reports

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build report (unit-tests)
          path: build/reports/kotlin-build/

  build-apks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: pando85/Android-Password-Store/.github/reusable-workflows/setup-gradle@b5a108731ef2c45cee4fe546f07eaf674948f6ce # main
        with:
          java-version: 21

      - name: Build debug APKs
        shell: bash
        run: ./gradlew assembleDebug

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build report (build-apks)
          path: build/reports/kotlin-build/

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: pando85/Android-Password-Store/.github/reusable-workflows/setup-gradle@b5a108731ef2c45cee4fe546f07eaf674948f6ce # main
        with:
          java-version: 21

      - name: Run Lint
        shell: bash
        run: ./gradlew lint

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build report (lint)
          path: build/reports/kotlin-build/
